{
 "title": "VGA Temperature",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Trau-1-2060",
   "type": "graph",
   "description": "Trau-1-2060",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "gpu_temperature_celsius{miner=\"Trau-1-2060\"}",
     "legendFormat": "gpu#{{ gpu }}"
    }
   ]
  },
  {
   "title": "Trau-2-Zotac-2060",
   "type": "graph",
   "description": "Trau-2-Zotac-2060",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "gpu_temperature_celsius{miner=\"Trau-2-Zotac-2060\"}",
     "legendFormat": "gpu#{{ gpu }}"
    }
   ]
  },
  {
   "title": "Trau-3-Zotac-2060",
   "type": "graph",
   "description": "Trau-3-Zotac-2060",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "gpu_temperature_celsius{miner=\"Trau-3-Zotac-2060\"}",
     "legendFormat": "gpu#{{ gpu }}"
    }
   ]
  }
 ]
}